# Generated by Django 3.0.6 on 2020-06-08 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='owner',
        ),
    ]
